// Code generated by go-swagger; DO NOT EDIT.

package zonecryptokey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/models"
)

// CreateCryptokeyReader is a Reader for the CreateCryptokey structure.
type CreateCryptokeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCryptokeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateCryptokeyCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateCryptokeyCreated creates a CreateCryptokeyCreated with default headers values
func NewCreateCryptokeyCreated() *CreateCryptokeyCreated {
	return &CreateCryptokeyCreated{}
}

/* CreateCryptokeyCreated describes a response with status code 201, with default header values.

Created
*/
type CreateCryptokeyCreated struct {
	Payload *models.Cryptokey
}

func (o *CreateCryptokeyCreated) Error() string {
	return fmt.Sprintf("[POST /servers/{server_id}/zones/{zone_id}/cryptokeys][%d] createCryptokeyCreated  %+v", 201, o.Payload)
}
func (o *CreateCryptokeyCreated) GetPayload() *models.Cryptokey {
	return o.Payload
}

func (o *CreateCryptokeyCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Cryptokey)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
