// Code generated by go-swagger; DO NOT EDIT.

package zonecryptokey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteCryptokeyReader is a Reader for the DeleteCryptokey structure.
type DeleteCryptokeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCryptokeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteCryptokeyNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteCryptokeyNoContent creates a DeleteCryptokeyNoContent with default headers values
func NewDeleteCryptokeyNoContent() *DeleteCryptokeyNoContent {
	return &DeleteCryptokeyNoContent{}
}

/* DeleteCryptokeyNoContent describes a response with status code 204, with default header values.

OK
*/
type DeleteCryptokeyNoContent struct {
}

func (o *DeleteCryptokeyNoContent) Error() string {
	return fmt.Sprintf("[DELETE /servers/{server_id}/zones/{zone_id}/cryptokeys/{cryptokey_id}][%d] deleteCryptokeyNoContent ", 204)
}

func (o *DeleteCryptokeyNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
