// Code generated by go-swagger; DO NOT EDIT.

package zonecryptokey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCryptokeyParams creates a new GetCryptokeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCryptokeyParams() *GetCryptokeyParams {
	return &GetCryptokeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCryptokeyParamsWithTimeout creates a new GetCryptokeyParams object
// with the ability to set a timeout on a request.
func NewGetCryptokeyParamsWithTimeout(timeout time.Duration) *GetCryptokeyParams {
	return &GetCryptokeyParams{
		timeout: timeout,
	}
}

// NewGetCryptokeyParamsWithContext creates a new GetCryptokeyParams object
// with the ability to set a context for a request.
func NewGetCryptokeyParamsWithContext(ctx context.Context) *GetCryptokeyParams {
	return &GetCryptokeyParams{
		Context: ctx,
	}
}

// NewGetCryptokeyParamsWithHTTPClient creates a new GetCryptokeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCryptokeyParamsWithHTTPClient(client *http.Client) *GetCryptokeyParams {
	return &GetCryptokeyParams{
		HTTPClient: client,
	}
}

/* GetCryptokeyParams contains all the parameters to send to the API endpoint
   for the get cryptokey operation.

   Typically these are written to a http.Request.
*/
type GetCryptokeyParams struct {

	/* CryptokeyID.

	   The id value of the CryptoKey
	*/
	CryptokeyID string

	/* ServerID.

	   The id of the server to retrieve
	*/
	ServerID string

	/* ZoneID.

	   The id of the zone to retrieve
	*/
	ZoneID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get cryptokey params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCryptokeyParams) WithDefaults() *GetCryptokeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get cryptokey params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCryptokeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get cryptokey params
func (o *GetCryptokeyParams) WithTimeout(timeout time.Duration) *GetCryptokeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cryptokey params
func (o *GetCryptokeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cryptokey params
func (o *GetCryptokeyParams) WithContext(ctx context.Context) *GetCryptokeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cryptokey params
func (o *GetCryptokeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cryptokey params
func (o *GetCryptokeyParams) WithHTTPClient(client *http.Client) *GetCryptokeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cryptokey params
func (o *GetCryptokeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCryptokeyID adds the cryptokeyID to the get cryptokey params
func (o *GetCryptokeyParams) WithCryptokeyID(cryptokeyID string) *GetCryptokeyParams {
	o.SetCryptokeyID(cryptokeyID)
	return o
}

// SetCryptokeyID adds the cryptokeyId to the get cryptokey params
func (o *GetCryptokeyParams) SetCryptokeyID(cryptokeyID string) {
	o.CryptokeyID = cryptokeyID
}

// WithServerID adds the serverID to the get cryptokey params
func (o *GetCryptokeyParams) WithServerID(serverID string) *GetCryptokeyParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the get cryptokey params
func (o *GetCryptokeyParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WithZoneID adds the zoneID to the get cryptokey params
func (o *GetCryptokeyParams) WithZoneID(zoneID string) *GetCryptokeyParams {
	o.SetZoneID(zoneID)
	return o
}

// SetZoneID adds the zoneId to the get cryptokey params
func (o *GetCryptokeyParams) SetZoneID(zoneID string) {
	o.ZoneID = zoneID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCryptokeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cryptokey_id
	if err := r.SetPathParam("cryptokey_id", o.CryptokeyID); err != nil {
		return err
	}

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}

	// path param zone_id
	if err := r.SetPathParam("zone_id", o.ZoneID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
