// Code generated by go-swagger; DO NOT EDIT.

package zonecryptokey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/models"
)

// GetCryptokeyReader is a Reader for the GetCryptokey structure.
type GetCryptokeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCryptokeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCryptokeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCryptokeyOK creates a GetCryptokeyOK with default headers values
func NewGetCryptokeyOK() *GetCryptokeyOK {
	return &GetCryptokeyOK{}
}

/* GetCryptokeyOK describes a response with status code 200, with default header values.

Cryptokey
*/
type GetCryptokeyOK struct {
	Payload *models.Cryptokey
}

func (o *GetCryptokeyOK) Error() string {
	return fmt.Sprintf("[GET /servers/{server_id}/zones/{zone_id}/cryptokeys/{cryptokey_id}][%d] getCryptokeyOK  %+v", 200, o.Payload)
}
func (o *GetCryptokeyOK) GetPayload() *models.Cryptokey {
	return o.Payload
}

func (o *GetCryptokeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Cryptokey)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
