// Code generated by go-swagger; DO NOT EDIT.

package zonecryptokey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListCryptokeysParams creates a new ListCryptokeysParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListCryptokeysParams() *ListCryptokeysParams {
	return &ListCryptokeysParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListCryptokeysParamsWithTimeout creates a new ListCryptokeysParams object
// with the ability to set a timeout on a request.
func NewListCryptokeysParamsWithTimeout(timeout time.Duration) *ListCryptokeysParams {
	return &ListCryptokeysParams{
		timeout: timeout,
	}
}

// NewListCryptokeysParamsWithContext creates a new ListCryptokeysParams object
// with the ability to set a context for a request.
func NewListCryptokeysParamsWithContext(ctx context.Context) *ListCryptokeysParams {
	return &ListCryptokeysParams{
		Context: ctx,
	}
}

// NewListCryptokeysParamsWithHTTPClient creates a new ListCryptokeysParams object
// with the ability to set a custom HTTPClient for a request.
func NewListCryptokeysParamsWithHTTPClient(client *http.Client) *ListCryptokeysParams {
	return &ListCryptokeysParams{
		HTTPClient: client,
	}
}

/* ListCryptokeysParams contains all the parameters to send to the API endpoint
   for the list cryptokeys operation.

   Typically these are written to a http.Request.
*/
type ListCryptokeysParams struct {

	/* ServerID.

	   The id of the server to retrieve
	*/
	ServerID string

	/* ZoneID.

	   The id of the zone to retrieve
	*/
	ZoneID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list cryptokeys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListCryptokeysParams) WithDefaults() *ListCryptokeysParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list cryptokeys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListCryptokeysParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list cryptokeys params
func (o *ListCryptokeysParams) WithTimeout(timeout time.Duration) *ListCryptokeysParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list cryptokeys params
func (o *ListCryptokeysParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list cryptokeys params
func (o *ListCryptokeysParams) WithContext(ctx context.Context) *ListCryptokeysParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list cryptokeys params
func (o *ListCryptokeysParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list cryptokeys params
func (o *ListCryptokeysParams) WithHTTPClient(client *http.Client) *ListCryptokeysParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list cryptokeys params
func (o *ListCryptokeysParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServerID adds the serverID to the list cryptokeys params
func (o *ListCryptokeysParams) WithServerID(serverID string) *ListCryptokeysParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the list cryptokeys params
func (o *ListCryptokeysParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WithZoneID adds the zoneID to the list cryptokeys params
func (o *ListCryptokeysParams) WithZoneID(zoneID string) *ListCryptokeysParams {
	o.SetZoneID(zoneID)
	return o
}

// SetZoneID adds the zoneId to the list cryptokeys params
func (o *ListCryptokeysParams) SetZoneID(zoneID string) {
	o.ZoneID = zoneID
}

// WriteToRequest writes these params to a swagger request
func (o *ListCryptokeysParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}

	// path param zone_id
	if err := r.SetPathParam("zone_id", o.ZoneID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
