// Code generated by go-swagger; DO NOT EDIT.

package zonecryptokey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ModifyCryptokeyReader is a Reader for the ModifyCryptokey structure.
type ModifyCryptokeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyCryptokeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewModifyCryptokeyNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewModifyCryptokeyNoContent creates a ModifyCryptokeyNoContent with default headers values
func NewModifyCryptokeyNoContent() *ModifyCryptokeyNoContent {
	return &ModifyCryptokeyNoContent{}
}

/* ModifyCryptokeyNoContent describes a response with status code 204, with default header values.

OK
*/
type ModifyCryptokeyNoContent struct {
}

func (o *ModifyCryptokeyNoContent) Error() string {
	return fmt.Sprintf("[PUT /servers/{server_id}/zones/{zone_id}/cryptokeys/{cryptokey_id}][%d] modifyCryptokeyNoContent ", 204)
}

func (o *ModifyCryptokeyNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
