// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/models"
)

// ErrorReader is a Reader for the Error structure.
type ErrorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ErrorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 400:
		result := NewErrorBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewErrorNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewErrorUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewErrorInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewErrorBadRequest creates a ErrorBadRequest with default headers values
func NewErrorBadRequest() *ErrorBadRequest {
	return &ErrorBadRequest{}
}

/* ErrorBadRequest describes a response with status code 400, with default header values.

The supplied request was not valid
*/
type ErrorBadRequest struct {
	Payload *models.Error
}

func (o *ErrorBadRequest) Error() string {
	return fmt.Sprintf("[GET /error][%d] errorBadRequest  %+v", 400, o.Payload)
}
func (o *ErrorBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ErrorBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewErrorNotFound creates a ErrorNotFound with default headers values
func NewErrorNotFound() *ErrorNotFound {
	return &ErrorNotFound{}
}

/* ErrorNotFound describes a response with status code 404, with default header values.

Requested item was not found
*/
type ErrorNotFound struct {
	Payload *models.Error
}

func (o *ErrorNotFound) Error() string {
	return fmt.Sprintf("[GET /error][%d] errorNotFound  %+v", 404, o.Payload)
}
func (o *ErrorNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *ErrorNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewErrorUnprocessableEntity creates a ErrorUnprocessableEntity with default headers values
func NewErrorUnprocessableEntity() *ErrorUnprocessableEntity {
	return &ErrorUnprocessableEntity{}
}

/* ErrorUnprocessableEntity describes a response with status code 422, with default header values.

The input to the operation was not valid
*/
type ErrorUnprocessableEntity struct {
	Payload *models.Error
}

func (o *ErrorUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /error][%d] errorUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *ErrorUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *ErrorUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewErrorInternalServerError creates a ErrorInternalServerError with default headers values
func NewErrorInternalServerError() *ErrorInternalServerError {
	return &ErrorInternalServerError{}
}

/* ErrorInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ErrorInternalServerError struct {
	Payload *models.Error
}

func (o *ErrorInternalServerError) Error() string {
	return fmt.Sprintf("[GET /error][%d] errorInternalServerError  %+v", 500, o.Payload)
}
func (o *ErrorInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *ErrorInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
