// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/client/autoprimary"
	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/client/config"
	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/client/operations"
	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/client/search"
	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/client/servers"
	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/client/stats"
	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/client/tsigkey"
	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/client/zonecryptokey"
	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/client/zonemetadata"
	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/client/zones"
)

// Default power DNS authoritative HTTP API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api/v1"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new power DNS authoritative HTTP API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *PowerDNSAuthoritativeHTTPAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new power DNS authoritative HTTP API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *PowerDNSAuthoritativeHTTPAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new power DNS authoritative HTTP API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *PowerDNSAuthoritativeHTTPAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(PowerDNSAuthoritativeHTTPAPI)
	cli.Transport = transport
	cli.Autoprimary = autoprimary.New(transport, formats)
	cli.Config = config.New(transport, formats)
	cli.Operations = operations.New(transport, formats)
	cli.Search = search.New(transport, formats)
	cli.Servers = servers.New(transport, formats)
	cli.Stats = stats.New(transport, formats)
	cli.Tsigkey = tsigkey.New(transport, formats)
	cli.Zonecryptokey = zonecryptokey.New(transport, formats)
	cli.Zonemetadata = zonemetadata.New(transport, formats)
	cli.Zones = zones.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// PowerDNSAuthoritativeHTTPAPI is a client for power DNS authoritative HTTP API
type PowerDNSAuthoritativeHTTPAPI struct {
	Autoprimary autoprimary.ClientService

	Config config.ClientService

	Operations operations.ClientService

	Search search.ClientService

	Servers servers.ClientService

	Stats stats.ClientService

	Tsigkey tsigkey.ClientService

	Zonecryptokey zonecryptokey.ClientService

	Zonemetadata zonemetadata.ClientService

	Zones zones.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *PowerDNSAuthoritativeHTTPAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Autoprimary.SetTransport(transport)
	c.Config.SetTransport(transport)
	c.Operations.SetTransport(transport)
	c.Search.SetTransport(transport)
	c.Servers.SetTransport(transport)
	c.Stats.SetTransport(transport)
	c.Tsigkey.SetTransport(transport)
	c.Zonecryptokey.SetTransport(transport)
	c.Zonemetadata.SetTransport(transport)
	c.Zones.SetTransport(transport)
}
