// Code generated by go-swagger; DO NOT EDIT.

package servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCacheFlushByNameParams creates a new CacheFlushByNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCacheFlushByNameParams() *CacheFlushByNameParams {
	return &CacheFlushByNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCacheFlushByNameParamsWithTimeout creates a new CacheFlushByNameParams object
// with the ability to set a timeout on a request.
func NewCacheFlushByNameParamsWithTimeout(timeout time.Duration) *CacheFlushByNameParams {
	return &CacheFlushByNameParams{
		timeout: timeout,
	}
}

// NewCacheFlushByNameParamsWithContext creates a new CacheFlushByNameParams object
// with the ability to set a context for a request.
func NewCacheFlushByNameParamsWithContext(ctx context.Context) *CacheFlushByNameParams {
	return &CacheFlushByNameParams{
		Context: ctx,
	}
}

// NewCacheFlushByNameParamsWithHTTPClient creates a new CacheFlushByNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewCacheFlushByNameParamsWithHTTPClient(client *http.Client) *CacheFlushByNameParams {
	return &CacheFlushByNameParams{
		HTTPClient: client,
	}
}

/* CacheFlushByNameParams contains all the parameters to send to the API endpoint
   for the cache flush by name operation.

   Typically these are written to a http.Request.
*/
type CacheFlushByNameParams struct {

	/* Domain.

	   The domain name to flush from the cache
	*/
	Domain string

	/* ServerID.

	   The id of the server to retrieve
	*/
	ServerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cache flush by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CacheFlushByNameParams) WithDefaults() *CacheFlushByNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cache flush by name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CacheFlushByNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cache flush by name params
func (o *CacheFlushByNameParams) WithTimeout(timeout time.Duration) *CacheFlushByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cache flush by name params
func (o *CacheFlushByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cache flush by name params
func (o *CacheFlushByNameParams) WithContext(ctx context.Context) *CacheFlushByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cache flush by name params
func (o *CacheFlushByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cache flush by name params
func (o *CacheFlushByNameParams) WithHTTPClient(client *http.Client) *CacheFlushByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cache flush by name params
func (o *CacheFlushByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomain adds the domain to the cache flush by name params
func (o *CacheFlushByNameParams) WithDomain(domain string) *CacheFlushByNameParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the cache flush by name params
func (o *CacheFlushByNameParams) SetDomain(domain string) {
	o.Domain = domain
}

// WithServerID adds the serverID to the cache flush by name params
func (o *CacheFlushByNameParams) WithServerID(serverID string) *CacheFlushByNameParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the cache flush by name params
func (o *CacheFlushByNameParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WriteToRequest writes these params to a swagger request
func (o *CacheFlushByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param domain
	qrDomain := o.Domain
	qDomain := qrDomain
	if qDomain != "" {

		if err := r.SetQueryParam("domain", qDomain); err != nil {
			return err
		}
	}

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
