// Code generated by go-swagger; DO NOT EDIT.

package zonemetadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteMetadataReader is a Reader for the DeleteMetadata structure.
type DeleteMetadataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMetadataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteMetadataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteMetadataOK creates a DeleteMetadataOK with default headers values
func NewDeleteMetadataOK() *DeleteMetadataOK {
	return &DeleteMetadataOK{}
}

/* DeleteMetadataOK describes a response with status code 200, with default header values.

OK
*/
type DeleteMetadataOK struct {
}

func (o *DeleteMetadataOK) Error() string {
	return fmt.Sprintf("[DELETE /servers/{server_id}/zones/{zone_id}/metadata/{metadata_kind}][%d] deleteMetadataOK ", 200)
}

func (o *DeleteMetadataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
