// Code generated by go-swagger; DO NOT EDIT.

package zonemetadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListMetadataParams creates a new ListMetadataParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListMetadataParams() *ListMetadataParams {
	return &ListMetadataParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListMetadataParamsWithTimeout creates a new ListMetadataParams object
// with the ability to set a timeout on a request.
func NewListMetadataParamsWithTimeout(timeout time.Duration) *ListMetadataParams {
	return &ListMetadataParams{
		timeout: timeout,
	}
}

// NewListMetadataParamsWithContext creates a new ListMetadataParams object
// with the ability to set a context for a request.
func NewListMetadataParamsWithContext(ctx context.Context) *ListMetadataParams {
	return &ListMetadataParams{
		Context: ctx,
	}
}

// NewListMetadataParamsWithHTTPClient creates a new ListMetadataParams object
// with the ability to set a custom HTTPClient for a request.
func NewListMetadataParamsWithHTTPClient(client *http.Client) *ListMetadataParams {
	return &ListMetadataParams{
		HTTPClient: client,
	}
}

/* ListMetadataParams contains all the parameters to send to the API endpoint
   for the list metadata operation.

   Typically these are written to a http.Request.
*/
type ListMetadataParams struct {

	/* ServerID.

	   The id of the server to retrieve
	*/
	ServerID string

	/* ZoneID.

	   The id of the zone to retrieve
	*/
	ZoneID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListMetadataParams) WithDefaults() *ListMetadataParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListMetadataParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list metadata params
func (o *ListMetadataParams) WithTimeout(timeout time.Duration) *ListMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list metadata params
func (o *ListMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list metadata params
func (o *ListMetadataParams) WithContext(ctx context.Context) *ListMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list metadata params
func (o *ListMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list metadata params
func (o *ListMetadataParams) WithHTTPClient(client *http.Client) *ListMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list metadata params
func (o *ListMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServerID adds the serverID to the list metadata params
func (o *ListMetadataParams) WithServerID(serverID string) *ListMetadataParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the list metadata params
func (o *ListMetadataParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WithZoneID adds the zoneID to the list metadata params
func (o *ListMetadataParams) WithZoneID(zoneID string) *ListMetadataParams {
	o.SetZoneID(zoneID)
	return o
}

// SetZoneID adds the zoneId to the list metadata params
func (o *ListMetadataParams) SetZoneID(zoneID string) {
	o.ZoneID = zoneID
}

// WriteToRequest writes these params to a swagger request
func (o *ListMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}

	// path param zone_id
	if err := r.SetPathParam("zone_id", o.ZoneID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
