// Code generated by go-swagger; DO NOT EDIT.

package zonemetadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new zonemetadata API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for zonemetadata API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateMetadata(params *CreateMetadataParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateMetadataNoContent, error)

	DeleteMetadata(params *DeleteMetadataParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteMetadataOK, error)

	GetMetadata(params *GetMetadataParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMetadataOK, error)

	ListMetadata(params *ListMetadataParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListMetadataOK, error)

	ModifyMetadata(params *ModifyMetadataParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ModifyMetadataOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CreateMetadata creates a set of metadata entries

  Creates a set of metadata entries of given kind for the zone. Existing metadata entries for the zone with the same kind are not overwritten.
*/
func (a *Client) CreateMetadata(params *CreateMetadataParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateMetadataNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateMetadataParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "createMetadata",
		Method:             "POST",
		PathPattern:        "/servers/{server_id}/zones/{zone_id}/metadata",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateMetadataReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateMetadataNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createMetadata: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DeleteMetadata deletes all items of a single kind of domain metadata
*/
func (a *Client) DeleteMetadata(params *DeleteMetadataParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteMetadataOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteMetadataParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "deleteMetadata",
		Method:             "DELETE",
		PathPattern:        "/servers/{server_id}/zones/{zone_id}/metadata/{metadata_kind}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteMetadataReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteMetadataOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteMetadata: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetMetadata gets the content of a single kind of domain metadata as a metadata object
*/
func (a *Client) GetMetadata(params *GetMetadataParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMetadataOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetMetadataParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getMetadata",
		Method:             "GET",
		PathPattern:        "/servers/{server_id}/zones/{zone_id}/metadata/{metadata_kind}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetMetadataReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetMetadataOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getMetadata: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ListMetadata gets all the metadata associated with the zone
*/
func (a *Client) ListMetadata(params *ListMetadataParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListMetadataOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListMetadataParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "listMetadata",
		Method:             "GET",
		PathPattern:        "/servers/{server_id}/zones/{zone_id}/metadata",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListMetadataReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListMetadataOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listMetadata: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ModifyMetadata replaces the content of a single kind of domain metadata

  Creates a set of metadata entries of given kind for the zone. Existing metadata entries for the zone with the same kind are removed.
*/
func (a *Client) ModifyMetadata(params *ModifyMetadataParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ModifyMetadataOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewModifyMetadataParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "modifyMetadata",
		Method:             "PUT",
		PathPattern:        "/servers/{server_id}/zones/{zone_id}/metadata/{metadata_kind}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ModifyMetadataReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ModifyMetadataOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for modifyMetadata: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
