// Code generated by go-swagger; DO NOT EDIT.

package tsigkey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/models"
)

// CreateTSIGKeyReader is a Reader for the CreateTSIGKey structure.
type CreateTSIGKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateTSIGKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateTSIGKeyCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 409:
		result := NewCreateTSIGKeyConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateTSIGKeyCreated creates a CreateTSIGKeyCreated with default headers values
func NewCreateTSIGKeyCreated() *CreateTSIGKeyCreated {
	return &CreateTSIGKeyCreated{}
}

/* CreateTSIGKeyCreated describes a response with status code 201, with default header values.

Created
*/
type CreateTSIGKeyCreated struct {
	Payload *models.TSIGKey
}

func (o *CreateTSIGKeyCreated) Error() string {
	return fmt.Sprintf("[POST /servers/{server_id}/tsigkeys][%d] createTSIGKeyCreated  %+v", 201, o.Payload)
}
func (o *CreateTSIGKeyCreated) GetPayload() *models.TSIGKey {
	return o.Payload
}

func (o *CreateTSIGKeyCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TSIGKey)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateTSIGKeyConflict creates a CreateTSIGKeyConflict with default headers values
func NewCreateTSIGKeyConflict() *CreateTSIGKeyConflict {
	return &CreateTSIGKeyConflict{}
}

/* CreateTSIGKeyConflict describes a response with status code 409, with default header values.

An item with this name already exists
*/
type CreateTSIGKeyConflict struct {
	Payload *models.Error
}

func (o *CreateTSIGKeyConflict) Error() string {
	return fmt.Sprintf("[POST /servers/{server_id}/tsigkeys][%d] createTSIGKeyConflict  %+v", 409, o.Payload)
}
func (o *CreateTSIGKeyConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateTSIGKeyConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
