// Code generated by go-swagger; DO NOT EDIT.

package tsigkey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/models"
)

// NewCreateTSIGKeyParams creates a new CreateTSIGKeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateTSIGKeyParams() *CreateTSIGKeyParams {
	return &CreateTSIGKeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateTSIGKeyParamsWithTimeout creates a new CreateTSIGKeyParams object
// with the ability to set a timeout on a request.
func NewCreateTSIGKeyParamsWithTimeout(timeout time.Duration) *CreateTSIGKeyParams {
	return &CreateTSIGKeyParams{
		timeout: timeout,
	}
}

// NewCreateTSIGKeyParamsWithContext creates a new CreateTSIGKeyParams object
// with the ability to set a context for a request.
func NewCreateTSIGKeyParamsWithContext(ctx context.Context) *CreateTSIGKeyParams {
	return &CreateTSIGKeyParams{
		Context: ctx,
	}
}

// NewCreateTSIGKeyParamsWithHTTPClient creates a new CreateTSIGKeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateTSIGKeyParamsWithHTTPClient(client *http.Client) *CreateTSIGKeyParams {
	return &CreateTSIGKeyParams{
		HTTPClient: client,
	}
}

/* CreateTSIGKeyParams contains all the parameters to send to the API endpoint
   for the create t s i g key operation.

   Typically these are written to a http.Request.
*/
type CreateTSIGKeyParams struct {

	/* ServerID.

	   The id of the server
	*/
	ServerID string

	/* Tsigkey.

	   The TSIGKey to add
	*/
	Tsigkey *models.TSIGKey

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create t s i g key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateTSIGKeyParams) WithDefaults() *CreateTSIGKeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create t s i g key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateTSIGKeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create t s i g key params
func (o *CreateTSIGKeyParams) WithTimeout(timeout time.Duration) *CreateTSIGKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create t s i g key params
func (o *CreateTSIGKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create t s i g key params
func (o *CreateTSIGKeyParams) WithContext(ctx context.Context) *CreateTSIGKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create t s i g key params
func (o *CreateTSIGKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create t s i g key params
func (o *CreateTSIGKeyParams) WithHTTPClient(client *http.Client) *CreateTSIGKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create t s i g key params
func (o *CreateTSIGKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServerID adds the serverID to the create t s i g key params
func (o *CreateTSIGKeyParams) WithServerID(serverID string) *CreateTSIGKeyParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the create t s i g key params
func (o *CreateTSIGKeyParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WithTsigkey adds the tsigkey to the create t s i g key params
func (o *CreateTSIGKeyParams) WithTsigkey(tsigkey *models.TSIGKey) *CreateTSIGKeyParams {
	o.SetTsigkey(tsigkey)
	return o
}

// SetTsigkey adds the tsigkey to the create t s i g key params
func (o *CreateTSIGKeyParams) SetTsigkey(tsigkey *models.TSIGKey) {
	o.Tsigkey = tsigkey
}

// WriteToRequest writes these params to a swagger request
func (o *CreateTSIGKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}
	if o.Tsigkey != nil {
		if err := r.SetBodyParam(o.Tsigkey); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
