// Code generated by go-swagger; DO NOT EDIT.

package tsigkey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteTSIGKeyReader is a Reader for the DeleteTSIGKey structure.
type DeleteTSIGKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTSIGKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteTSIGKeyNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteTSIGKeyNoContent creates a DeleteTSIGKeyNoContent with default headers values
func NewDeleteTSIGKeyNoContent() *DeleteTSIGKeyNoContent {
	return &DeleteTSIGKeyNoContent{}
}

/* DeleteTSIGKeyNoContent describes a response with status code 204, with default header values.

OK, key was deleted
*/
type DeleteTSIGKeyNoContent struct {
}

func (o *DeleteTSIGKeyNoContent) Error() string {
	return fmt.Sprintf("[DELETE /servers/{server_id}/tsigkeys/{tsigkey_id}][%d] deleteTSIGKeyNoContent ", 204)
}

func (o *DeleteTSIGKeyNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
