// Code generated by go-swagger; DO NOT EDIT.

package tsigkey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTSIGKeyParams creates a new DeleteTSIGKeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteTSIGKeyParams() *DeleteTSIGKeyParams {
	return &DeleteTSIGKeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTSIGKeyParamsWithTimeout creates a new DeleteTSIGKeyParams object
// with the ability to set a timeout on a request.
func NewDeleteTSIGKeyParamsWithTimeout(timeout time.Duration) *DeleteTSIGKeyParams {
	return &DeleteTSIGKeyParams{
		timeout: timeout,
	}
}

// NewDeleteTSIGKeyParamsWithContext creates a new DeleteTSIGKeyParams object
// with the ability to set a context for a request.
func NewDeleteTSIGKeyParamsWithContext(ctx context.Context) *DeleteTSIGKeyParams {
	return &DeleteTSIGKeyParams{
		Context: ctx,
	}
}

// NewDeleteTSIGKeyParamsWithHTTPClient creates a new DeleteTSIGKeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteTSIGKeyParamsWithHTTPClient(client *http.Client) *DeleteTSIGKeyParams {
	return &DeleteTSIGKeyParams{
		HTTPClient: client,
	}
}

/* DeleteTSIGKeyParams contains all the parameters to send to the API endpoint
   for the delete t s i g key operation.

   Typically these are written to a http.Request.
*/
type DeleteTSIGKeyParams struct {

	/* ServerID.

	   The id of the server to retrieve the key from
	*/
	ServerID string

	/* TsigkeyID.

	   The id of the TSIGkey. Should match the "id" field in the TSIGKey object
	*/
	TsigkeyID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete t s i g key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTSIGKeyParams) WithDefaults() *DeleteTSIGKeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete t s i g key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTSIGKeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete t s i g key params
func (o *DeleteTSIGKeyParams) WithTimeout(timeout time.Duration) *DeleteTSIGKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete t s i g key params
func (o *DeleteTSIGKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete t s i g key params
func (o *DeleteTSIGKeyParams) WithContext(ctx context.Context) *DeleteTSIGKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete t s i g key params
func (o *DeleteTSIGKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete t s i g key params
func (o *DeleteTSIGKeyParams) WithHTTPClient(client *http.Client) *DeleteTSIGKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete t s i g key params
func (o *DeleteTSIGKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServerID adds the serverID to the delete t s i g key params
func (o *DeleteTSIGKeyParams) WithServerID(serverID string) *DeleteTSIGKeyParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the delete t s i g key params
func (o *DeleteTSIGKeyParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WithTsigkeyID adds the tsigkeyID to the delete t s i g key params
func (o *DeleteTSIGKeyParams) WithTsigkeyID(tsigkeyID string) *DeleteTSIGKeyParams {
	o.SetTsigkeyID(tsigkeyID)
	return o
}

// SetTsigkeyID adds the tsigkeyId to the delete t s i g key params
func (o *DeleteTSIGKeyParams) SetTsigkeyID(tsigkeyID string) {
	o.TsigkeyID = tsigkeyID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTSIGKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}

	// path param tsigkey_id
	if err := r.SetPathParam("tsigkey_id", o.TsigkeyID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
