// Code generated by go-swagger; DO NOT EDIT.

package tsigkey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListTSIGKeysParams creates a new ListTSIGKeysParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListTSIGKeysParams() *ListTSIGKeysParams {
	return &ListTSIGKeysParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListTSIGKeysParamsWithTimeout creates a new ListTSIGKeysParams object
// with the ability to set a timeout on a request.
func NewListTSIGKeysParamsWithTimeout(timeout time.Duration) *ListTSIGKeysParams {
	return &ListTSIGKeysParams{
		timeout: timeout,
	}
}

// NewListTSIGKeysParamsWithContext creates a new ListTSIGKeysParams object
// with the ability to set a context for a request.
func NewListTSIGKeysParamsWithContext(ctx context.Context) *ListTSIGKeysParams {
	return &ListTSIGKeysParams{
		Context: ctx,
	}
}

// NewListTSIGKeysParamsWithHTTPClient creates a new ListTSIGKeysParams object
// with the ability to set a custom HTTPClient for a request.
func NewListTSIGKeysParamsWithHTTPClient(client *http.Client) *ListTSIGKeysParams {
	return &ListTSIGKeysParams{
		HTTPClient: client,
	}
}

/* ListTSIGKeysParams contains all the parameters to send to the API endpoint
   for the list t s i g keys operation.

   Typically these are written to a http.Request.
*/
type ListTSIGKeysParams struct {

	/* ServerID.

	   The id of the server
	*/
	ServerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list t s i g keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListTSIGKeysParams) WithDefaults() *ListTSIGKeysParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list t s i g keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListTSIGKeysParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list t s i g keys params
func (o *ListTSIGKeysParams) WithTimeout(timeout time.Duration) *ListTSIGKeysParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list t s i g keys params
func (o *ListTSIGKeysParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list t s i g keys params
func (o *ListTSIGKeysParams) WithContext(ctx context.Context) *ListTSIGKeysParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list t s i g keys params
func (o *ListTSIGKeysParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list t s i g keys params
func (o *ListTSIGKeysParams) WithHTTPClient(client *http.Client) *ListTSIGKeysParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list t s i g keys params
func (o *ListTSIGKeysParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServerID adds the serverID to the list t s i g keys params
func (o *ListTSIGKeysParams) WithServerID(serverID string) *ListTSIGKeysParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the list t s i g keys params
func (o *ListTSIGKeysParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WriteToRequest writes these params to a swagger request
func (o *ListTSIGKeysParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
