// Code generated by go-swagger; DO NOT EDIT.

package tsigkey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/models"
)

// NewPutTSIGKeyParams creates a new PutTSIGKeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutTSIGKeyParams() *PutTSIGKeyParams {
	return &PutTSIGKeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutTSIGKeyParamsWithTimeout creates a new PutTSIGKeyParams object
// with the ability to set a timeout on a request.
func NewPutTSIGKeyParamsWithTimeout(timeout time.Duration) *PutTSIGKeyParams {
	return &PutTSIGKeyParams{
		timeout: timeout,
	}
}

// NewPutTSIGKeyParamsWithContext creates a new PutTSIGKeyParams object
// with the ability to set a context for a request.
func NewPutTSIGKeyParamsWithContext(ctx context.Context) *PutTSIGKeyParams {
	return &PutTSIGKeyParams{
		Context: ctx,
	}
}

// NewPutTSIGKeyParamsWithHTTPClient creates a new PutTSIGKeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutTSIGKeyParamsWithHTTPClient(client *http.Client) *PutTSIGKeyParams {
	return &PutTSIGKeyParams{
		HTTPClient: client,
	}
}

/* PutTSIGKeyParams contains all the parameters to send to the API endpoint
   for the put t s i g key operation.

   Typically these are written to a http.Request.
*/
type PutTSIGKeyParams struct {

	/* ServerID.

	   The id of the server to retrieve the key from
	*/
	ServerID string

	/* Tsigkey.

	   A (possibly stripped down) TSIGKey object with the new values
	*/
	Tsigkey *models.TSIGKey

	/* TsigkeyID.

	   The id of the TSIGkey. Should match the "id" field in the TSIGKey object
	*/
	TsigkeyID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put t s i g key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutTSIGKeyParams) WithDefaults() *PutTSIGKeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put t s i g key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutTSIGKeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put t s i g key params
func (o *PutTSIGKeyParams) WithTimeout(timeout time.Duration) *PutTSIGKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put t s i g key params
func (o *PutTSIGKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put t s i g key params
func (o *PutTSIGKeyParams) WithContext(ctx context.Context) *PutTSIGKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put t s i g key params
func (o *PutTSIGKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put t s i g key params
func (o *PutTSIGKeyParams) WithHTTPClient(client *http.Client) *PutTSIGKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put t s i g key params
func (o *PutTSIGKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServerID adds the serverID to the put t s i g key params
func (o *PutTSIGKeyParams) WithServerID(serverID string) *PutTSIGKeyParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the put t s i g key params
func (o *PutTSIGKeyParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WithTsigkey adds the tsigkey to the put t s i g key params
func (o *PutTSIGKeyParams) WithTsigkey(tsigkey *models.TSIGKey) *PutTSIGKeyParams {
	o.SetTsigkey(tsigkey)
	return o
}

// SetTsigkey adds the tsigkey to the put t s i g key params
func (o *PutTSIGKeyParams) SetTsigkey(tsigkey *models.TSIGKey) {
	o.Tsigkey = tsigkey
}

// WithTsigkeyID adds the tsigkeyID to the put t s i g key params
func (o *PutTSIGKeyParams) WithTsigkeyID(tsigkeyID string) *PutTSIGKeyParams {
	o.SetTsigkeyID(tsigkeyID)
	return o
}

// SetTsigkeyID adds the tsigkeyId to the put t s i g key params
func (o *PutTSIGKeyParams) SetTsigkeyID(tsigkeyID string) {
	o.TsigkeyID = tsigkeyID
}

// WriteToRequest writes these params to a swagger request
func (o *PutTSIGKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}
	if o.Tsigkey != nil {
		if err := r.SetBodyParam(o.Tsigkey); err != nil {
			return err
		}
	}

	// path param tsigkey_id
	if err := r.SetPathParam("tsigkey_id", o.TsigkeyID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
