// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Autoprimary Autoprimary server
//
// An autoprimary server that can provision new domains.
//
// swagger:model Autoprimary
type Autoprimary struct {

	// Account name for the autoprimary server
	Account string `json:"account,omitempty"`

	// IP address of the autoprimary server
	IP string `json:"ip,omitempty"`

	// DNS name of the autoprimary server
	Nameserver string `json:"nameserver,omitempty"`
}

// Validate validates this autoprimary
func (m *Autoprimary) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this autoprimary based on context it is used
func (m *Autoprimary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Autoprimary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Autoprimary) UnmarshalBinary(b []byte) error {
	var res Autoprimary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
