// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigSetting ConfigSetting
//
// swagger:model ConfigSetting
type ConfigSetting struct {

	// set to "ConfigSetting"
	Name string `json:"name,omitempty"`

	// The name of this setting (e.g. ‘webserver-port’)
	Type string `json:"type,omitempty"`

	// The value of setting name
	Value string `json:"value,omitempty"`
}

// Validate validates this config setting
func (m *ConfigSetting) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this config setting based on context it is used
func (m *ConfigSetting) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConfigSetting) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigSetting) UnmarshalBinary(b []byte) error {
	var res ConfigSetting
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
