// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Server Server
//
// swagger:model Server
type Server struct {

	// The API endpoint for this server’s configuration
	ConfigURL string `json:"config_url,omitempty"`

	// “recursor” for the PowerDNS Recursor and “authoritative” for the Authoritative Server
	DaemonType string `json:"daemon_type,omitempty"`

	// The id of the server, “localhost”
	ID string `json:"id,omitempty"`

	// Set to “Server”
	Type string `json:"type,omitempty"`

	// The API endpoint for this server
	URL string `json:"url,omitempty"`

	// The version of the server software
	Version string `json:"version,omitempty"`

	// The API endpoint for this server’s zones
	ZonesURL string `json:"zones_url,omitempty"`
}

// Validate validates this server
func (m *Server) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this server based on context it is used
func (m *Server) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Server) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Server) UnmarshalBinary(b []byte) error {
	var res Server
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
