// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SimpleStatisticItem SimpleStatisticItem
//
// swagger:model SimpleStatisticItem
type SimpleStatisticItem struct {

	// Item name
	Name string `json:"name,omitempty"`

	// Item value
	Value string `json:"value,omitempty"`
}

// Validate validates this simple statistic item
func (m *SimpleStatisticItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this simple statistic item based on context it is used
func (m *SimpleStatisticItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SimpleStatisticItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SimpleStatisticItem) UnmarshalBinary(b []byte) error {
	var res SimpleStatisticItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
