// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StatisticItem StatisticItem
//
// swagger:model StatisticItem
type StatisticItem struct {

	// Item name
	Name string `json:"name,omitempty"`

	// set to "StatisticItem"
	Type string `json:"type,omitempty"`

	// Item value
	Value string `json:"value,omitempty"`
}

// Validate validates this statistic item
func (m *StatisticItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this statistic item based on context it is used
func (m *StatisticItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StatisticItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StatisticItem) UnmarshalBinary(b []byte) error {
	var res StatisticItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
