// Code generated by go-swagger; DO NOT EDIT.

package autoprimary

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new autoprimary API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for autoprimary API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateAutoprimary(params *CreateAutoprimaryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateAutoprimaryCreated, error)

	DeleteAutoprimary(params *DeleteAutoprimaryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteAutoprimaryNoContent, error)

	GetAutoprimaries(params *GetAutoprimariesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetAutoprimariesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CreateAutoprimary adds an autoprimary

  This methods add a new autoprimary server.
*/
func (a *Client) CreateAutoprimary(params *CreateAutoprimaryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateAutoprimaryCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateAutoprimaryParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "createAutoprimary",
		Method:             "POST",
		PathPattern:        "/servers/{server_id}/autoprimaries",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateAutoprimaryReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateAutoprimaryCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createAutoprimary: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DeleteAutoprimary deletes the autoprimary entry
*/
func (a *Client) DeleteAutoprimary(params *DeleteAutoprimaryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteAutoprimaryNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteAutoprimaryParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "deleteAutoprimary",
		Method:             "DELETE",
		PathPattern:        "/servers/{server_id}/autoprimaries/{ip}/{nameserver}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteAutoprimaryReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteAutoprimaryNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteAutoprimary: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetAutoprimaries gets a list of autoprimaries
*/
func (a *Client) GetAutoprimaries(params *GetAutoprimariesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetAutoprimariesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAutoprimariesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getAutoprimaries",
		Method:             "GET",
		PathPattern:        "/servers/{server_id}/autoprimaries",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAutoprimariesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAutoprimariesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getAutoprimaries: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
