// Code generated by go-swagger; DO NOT EDIT.

package autoprimary

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/models"
)

// NewCreateAutoprimaryParams creates a new CreateAutoprimaryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateAutoprimaryParams() *CreateAutoprimaryParams {
	return &CreateAutoprimaryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAutoprimaryParamsWithTimeout creates a new CreateAutoprimaryParams object
// with the ability to set a timeout on a request.
func NewCreateAutoprimaryParamsWithTimeout(timeout time.Duration) *CreateAutoprimaryParams {
	return &CreateAutoprimaryParams{
		timeout: timeout,
	}
}

// NewCreateAutoprimaryParamsWithContext creates a new CreateAutoprimaryParams object
// with the ability to set a context for a request.
func NewCreateAutoprimaryParamsWithContext(ctx context.Context) *CreateAutoprimaryParams {
	return &CreateAutoprimaryParams{
		Context: ctx,
	}
}

// NewCreateAutoprimaryParamsWithHTTPClient creates a new CreateAutoprimaryParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateAutoprimaryParamsWithHTTPClient(client *http.Client) *CreateAutoprimaryParams {
	return &CreateAutoprimaryParams{
		HTTPClient: client,
	}
}

/* CreateAutoprimaryParams contains all the parameters to send to the API endpoint
   for the create autoprimary operation.

   Typically these are written to a http.Request.
*/
type CreateAutoprimaryParams struct {

	/* Autoprimary.

	   autoprimary entry to add
	*/
	Autoprimary *models.Autoprimary

	/* ServerID.

	   The id of the server to manage the list of autoprimaries on
	*/
	ServerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create autoprimary params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAutoprimaryParams) WithDefaults() *CreateAutoprimaryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create autoprimary params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAutoprimaryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create autoprimary params
func (o *CreateAutoprimaryParams) WithTimeout(timeout time.Duration) *CreateAutoprimaryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create autoprimary params
func (o *CreateAutoprimaryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create autoprimary params
func (o *CreateAutoprimaryParams) WithContext(ctx context.Context) *CreateAutoprimaryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create autoprimary params
func (o *CreateAutoprimaryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create autoprimary params
func (o *CreateAutoprimaryParams) WithHTTPClient(client *http.Client) *CreateAutoprimaryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create autoprimary params
func (o *CreateAutoprimaryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAutoprimary adds the autoprimary to the create autoprimary params
func (o *CreateAutoprimaryParams) WithAutoprimary(autoprimary *models.Autoprimary) *CreateAutoprimaryParams {
	o.SetAutoprimary(autoprimary)
	return o
}

// SetAutoprimary adds the autoprimary to the create autoprimary params
func (o *CreateAutoprimaryParams) SetAutoprimary(autoprimary *models.Autoprimary) {
	o.Autoprimary = autoprimary
}

// WithServerID adds the serverID to the create autoprimary params
func (o *CreateAutoprimaryParams) WithServerID(serverID string) *CreateAutoprimaryParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the create autoprimary params
func (o *CreateAutoprimaryParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAutoprimaryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Autoprimary != nil {
		if err := r.SetBodyParam(o.Autoprimary); err != nil {
			return err
		}
	}

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
