// Code generated by go-swagger; DO NOT EDIT.

package autoprimary

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateAutoprimaryReader is a Reader for the CreateAutoprimary structure.
type CreateAutoprimaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAutoprimaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateAutoprimaryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateAutoprimaryCreated creates a CreateAutoprimaryCreated with default headers values
func NewCreateAutoprimaryCreated() *CreateAutoprimaryCreated {
	return &CreateAutoprimaryCreated{}
}

/* CreateAutoprimaryCreated describes a response with status code 201, with default header values.

Created
*/
type CreateAutoprimaryCreated struct {
}

func (o *CreateAutoprimaryCreated) Error() string {
	return fmt.Sprintf("[POST /servers/{server_id}/autoprimaries][%d] createAutoprimaryCreated ", 201)
}

func (o *CreateAutoprimaryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
