// Code generated by go-swagger; DO NOT EDIT.

package autoprimary

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAutoprimaryReader is a Reader for the DeleteAutoprimary structure.
type DeleteAutoprimaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAutoprimaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAutoprimaryNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAutoprimaryNoContent creates a DeleteAutoprimaryNoContent with default headers values
func NewDeleteAutoprimaryNoContent() *DeleteAutoprimaryNoContent {
	return &DeleteAutoprimaryNoContent{}
}

/* DeleteAutoprimaryNoContent describes a response with status code 204, with default header values.

OK, key was deleted
*/
type DeleteAutoprimaryNoContent struct {
}

func (o *DeleteAutoprimaryNoContent) Error() string {
	return fmt.Sprintf("[DELETE /servers/{server_id}/autoprimaries/{ip}/{nameserver}][%d] deleteAutoprimaryNoContent ", 204)
}

func (o *DeleteAutoprimaryNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
