// Code generated by go-swagger; DO NOT EDIT.

package autoprimary

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAutoprimariesParams creates a new GetAutoprimariesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAutoprimariesParams() *GetAutoprimariesParams {
	return &GetAutoprimariesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAutoprimariesParamsWithTimeout creates a new GetAutoprimariesParams object
// with the ability to set a timeout on a request.
func NewGetAutoprimariesParamsWithTimeout(timeout time.Duration) *GetAutoprimariesParams {
	return &GetAutoprimariesParams{
		timeout: timeout,
	}
}

// NewGetAutoprimariesParamsWithContext creates a new GetAutoprimariesParams object
// with the ability to set a context for a request.
func NewGetAutoprimariesParamsWithContext(ctx context.Context) *GetAutoprimariesParams {
	return &GetAutoprimariesParams{
		Context: ctx,
	}
}

// NewGetAutoprimariesParamsWithHTTPClient creates a new GetAutoprimariesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAutoprimariesParamsWithHTTPClient(client *http.Client) *GetAutoprimariesParams {
	return &GetAutoprimariesParams{
		HTTPClient: client,
	}
}

/* GetAutoprimariesParams contains all the parameters to send to the API endpoint
   for the get autoprimaries operation.

   Typically these are written to a http.Request.
*/
type GetAutoprimariesParams struct {

	/* ServerID.

	   The id of the server to manage the list of autoprimaries on
	*/
	ServerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get autoprimaries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAutoprimariesParams) WithDefaults() *GetAutoprimariesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get autoprimaries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAutoprimariesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get autoprimaries params
func (o *GetAutoprimariesParams) WithTimeout(timeout time.Duration) *GetAutoprimariesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get autoprimaries params
func (o *GetAutoprimariesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get autoprimaries params
func (o *GetAutoprimariesParams) WithContext(ctx context.Context) *GetAutoprimariesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get autoprimaries params
func (o *GetAutoprimariesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get autoprimaries params
func (o *GetAutoprimariesParams) WithHTTPClient(client *http.Client) *GetAutoprimariesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get autoprimaries params
func (o *GetAutoprimariesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServerID adds the serverID to the get autoprimaries params
func (o *GetAutoprimariesParams) WithServerID(serverID string) *GetAutoprimariesParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the get autoprimaries params
func (o *GetAutoprimariesParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAutoprimariesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
