// Code generated by go-swagger; DO NOT EDIT.

package autoprimary

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/models"
)

// GetAutoprimariesReader is a Reader for the GetAutoprimaries structure.
type GetAutoprimariesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAutoprimariesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAutoprimariesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAutoprimariesOK creates a GetAutoprimariesOK with default headers values
func NewGetAutoprimariesOK() *GetAutoprimariesOK {
	return &GetAutoprimariesOK{}
}

/* GetAutoprimariesOK describes a response with status code 200, with default header values.

OK.
*/
type GetAutoprimariesOK struct {
	Payload *models.Autoprimary
}

func (o *GetAutoprimariesOK) Error() string {
	return fmt.Sprintf("[GET /servers/{server_id}/autoprimaries][%d] getAutoprimariesOK  %+v", 200, o.Payload)
}
func (o *GetAutoprimariesOK) GetPayload() *models.Autoprimary {
	return o.Payload
}

func (o *GetAutoprimariesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Autoprimary)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
