# Terraform Provider testing workflow.
name: Tests

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
  pull_request:
    paths-ignore:
      - "README.md"
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  # Ensure project builds before running testing matrix
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: latest

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
          cache: true
      # We need the latest version of Terraform for our documentation generation to use
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_wrapper: false
      - run: make generate
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'make generate' command and commit."; exit 1)

  setup_test_env:
    name: Setup Acceptance Test Environment
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      pdsn_server_url: ${{ steps.server_address.outputs.url }}
      server_name: ${{ steps.random.outputs.server_name }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: random
        run: |
          random_mysql_root_password=$(uuidgen)
          echo "::add-mask::$random_mysql_root_password"
          echo "mysql_root_password=$random_mysql_root_password" >> $GITHUB_OUTPUT
          random_pdns_webserver_password=$(uuidgen)
          echo "::add-mask::$random_pdns_webserver_password"
          echo "pdns_webserver_password=$random_pdns_webserver_password" >> $GITHUB_OUTPUT
          echo "server_name=tf-pdns-$(uuidgen)" >> $GITHUB_OUTPUT
      - uses: chuhlomin/render-template@a7c644e341797d050d1cb24332d83791b9a46dae # v1.12
        with:
          template: files/cloud-config.yaml
          vars: |
            mysql_root_password: ${{ steps.random.outputs.mysql_root_password }}
            pdns_api_key: ${{ secrets.POWERDNS_API_KEY }}
            pdns_webserver_password: ${{ steps.random.outputs.pdns_webserver_password }}
          result_path: cloud-config.yaml
      - uses: hetznercloud/setup-hcloud@ac9e7d74fb41a3ca44a6a3da123bd5aa70731e3a # v2.0.0
      - run: |
          hcloud server create --name ${{ steps.random.outputs.server_name }} \
           --type cx23 \
           --image docker-ce \
           --ssh-key terraform-provider-powerdns \
           --location nbg1 \
           --user-data-from-file cloud-config.yaml
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      - id: server_address
        run: echo "url=http://$(hcloud server ip ${{ steps.random.outputs.server_name }}):8081/api/v1" >> $GITHUB_OUTPUT
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      # Give the test server some time to start its services
      - run: sleep 60
      - run: 'curl -H "X-API-Key: ${{ secrets.POWERDNS_API_KEY }}" -d @files/example-zone.json ${{ steps.server_address.outputs.url }}/servers/localhost/zones'

  # Run acceptance tests in a matrix with Terraform CLI versions
  test:
    name: "Acceptance Tests: Terraform ${{ matrix.terraform }}"
    needs:
      - build
      - setup_test_env
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # Terraform versions
        terraform:
          - "1.13.*"
          - "1.14.*"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - env:
          TF_ACC: "1"
          POWERDNS_API_KEY: ${{ secrets.POWERDNS_API_KEY }}
          POWERDNS_SERVER_URL: ${{ needs.setup_test_env.outputs.pdsn_server_url }}
        run: go test -v -cover ./internal/provider/
        timeout-minutes: 10

  teardown_test_env:
    name: Teardown Acceptance Test Environment
    runs-on: ubuntu-latest
    needs:
      - setup_test_env
      - test
    if: ${{ always() }}
    steps:
      - uses: hetznercloud/setup-hcloud@ac9e7d74fb41a3ca44a6a3da123bd5aa70731e3a # v2.0.0
      - run: |
          hcloud server delete ${{ needs.setup_test_env.outputs.server_name }}
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
