// Code generated by go-swagger; DO NOT EDIT.

package zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AxfrRetrieveZoneReader is a Reader for the AxfrRetrieveZone structure.
type AxfrRetrieveZoneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AxfrRetrieveZoneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAxfrRetrieveZoneOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAxfrRetrieveZoneOK creates a AxfrRetrieveZoneOK with default headers values
func NewAxfrRetrieveZoneOK() *AxfrRetrieveZoneOK {
	return &AxfrRetrieveZoneOK{}
}

/* AxfrRetrieveZoneOK describes a response with status code 200, with default header values.

OK
*/
type AxfrRetrieveZoneOK struct {
}

func (o *AxfrRetrieveZoneOK) Error() string {
	return fmt.Sprintf("[PUT /servers/{server_id}/zones/{zone_id}/axfr-retrieve][%d] axfrRetrieveZoneOK ", 200)
}

func (o *AxfrRetrieveZoneOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
