// Code generated by go-swagger; DO NOT EDIT.

package zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAxfrExportZoneParams creates a new AxfrExportZoneParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAxfrExportZoneParams() *AxfrExportZoneParams {
	return &AxfrExportZoneParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAxfrExportZoneParamsWithTimeout creates a new AxfrExportZoneParams object
// with the ability to set a timeout on a request.
func NewAxfrExportZoneParamsWithTimeout(timeout time.Duration) *AxfrExportZoneParams {
	return &AxfrExportZoneParams{
		timeout: timeout,
	}
}

// NewAxfrExportZoneParamsWithContext creates a new AxfrExportZoneParams object
// with the ability to set a context for a request.
func NewAxfrExportZoneParamsWithContext(ctx context.Context) *AxfrExportZoneParams {
	return &AxfrExportZoneParams{
		Context: ctx,
	}
}

// NewAxfrExportZoneParamsWithHTTPClient creates a new AxfrExportZoneParams object
// with the ability to set a custom HTTPClient for a request.
func NewAxfrExportZoneParamsWithHTTPClient(client *http.Client) *AxfrExportZoneParams {
	return &AxfrExportZoneParams{
		HTTPClient: client,
	}
}

/* AxfrExportZoneParams contains all the parameters to send to the API endpoint
   for the axfr export zone operation.

   Typically these are written to a http.Request.
*/
type AxfrExportZoneParams struct {

	/* ServerID.

	   The id of the server to retrieve
	*/
	ServerID string

	/* ZoneID.

	   The id of the zone to retrieve
	*/
	ZoneID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the axfr export zone params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AxfrExportZoneParams) WithDefaults() *AxfrExportZoneParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the axfr export zone params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AxfrExportZoneParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the axfr export zone params
func (o *AxfrExportZoneParams) WithTimeout(timeout time.Duration) *AxfrExportZoneParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the axfr export zone params
func (o *AxfrExportZoneParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the axfr export zone params
func (o *AxfrExportZoneParams) WithContext(ctx context.Context) *AxfrExportZoneParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the axfr export zone params
func (o *AxfrExportZoneParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the axfr export zone params
func (o *AxfrExportZoneParams) WithHTTPClient(client *http.Client) *AxfrExportZoneParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the axfr export zone params
func (o *AxfrExportZoneParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServerID adds the serverID to the axfr export zone params
func (o *AxfrExportZoneParams) WithServerID(serverID string) *AxfrExportZoneParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the axfr export zone params
func (o *AxfrExportZoneParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WithZoneID adds the zoneID to the axfr export zone params
func (o *AxfrExportZoneParams) WithZoneID(zoneID string) *AxfrExportZoneParams {
	o.SetZoneID(zoneID)
	return o
}

// SetZoneID adds the zoneId to the axfr export zone params
func (o *AxfrExportZoneParams) SetZoneID(zoneID string) {
	o.ZoneID = zoneID
}

// WriteToRequest writes these params to a swagger request
func (o *AxfrExportZoneParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}

	// path param zone_id
	if err := r.SetPathParam("zone_id", o.ZoneID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
