// Code generated by go-swagger; DO NOT EDIT.

package zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAxfrRetrieveZoneParams creates a new AxfrRetrieveZoneParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAxfrRetrieveZoneParams() *AxfrRetrieveZoneParams {
	return &AxfrRetrieveZoneParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAxfrRetrieveZoneParamsWithTimeout creates a new AxfrRetrieveZoneParams object
// with the ability to set a timeout on a request.
func NewAxfrRetrieveZoneParamsWithTimeout(timeout time.Duration) *AxfrRetrieveZoneParams {
	return &AxfrRetrieveZoneParams{
		timeout: timeout,
	}
}

// NewAxfrRetrieveZoneParamsWithContext creates a new AxfrRetrieveZoneParams object
// with the ability to set a context for a request.
func NewAxfrRetrieveZoneParamsWithContext(ctx context.Context) *AxfrRetrieveZoneParams {
	return &AxfrRetrieveZoneParams{
		Context: ctx,
	}
}

// NewAxfrRetrieveZoneParamsWithHTTPClient creates a new AxfrRetrieveZoneParams object
// with the ability to set a custom HTTPClient for a request.
func NewAxfrRetrieveZoneParamsWithHTTPClient(client *http.Client) *AxfrRetrieveZoneParams {
	return &AxfrRetrieveZoneParams{
		HTTPClient: client,
	}
}

/* AxfrRetrieveZoneParams contains all the parameters to send to the API endpoint
   for the axfr retrieve zone operation.

   Typically these are written to a http.Request.
*/
type AxfrRetrieveZoneParams struct {

	/* ServerID.

	   The id of the server to retrieve
	*/
	ServerID string

	/* ZoneID.

	   The id of the zone to retrieve
	*/
	ZoneID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the axfr retrieve zone params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AxfrRetrieveZoneParams) WithDefaults() *AxfrRetrieveZoneParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the axfr retrieve zone params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AxfrRetrieveZoneParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the axfr retrieve zone params
func (o *AxfrRetrieveZoneParams) WithTimeout(timeout time.Duration) *AxfrRetrieveZoneParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the axfr retrieve zone params
func (o *AxfrRetrieveZoneParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the axfr retrieve zone params
func (o *AxfrRetrieveZoneParams) WithContext(ctx context.Context) *AxfrRetrieveZoneParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the axfr retrieve zone params
func (o *AxfrRetrieveZoneParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the axfr retrieve zone params
func (o *AxfrRetrieveZoneParams) WithHTTPClient(client *http.Client) *AxfrRetrieveZoneParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the axfr retrieve zone params
func (o *AxfrRetrieveZoneParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServerID adds the serverID to the axfr retrieve zone params
func (o *AxfrRetrieveZoneParams) WithServerID(serverID string) *AxfrRetrieveZoneParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the axfr retrieve zone params
func (o *AxfrRetrieveZoneParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WithZoneID adds the zoneID to the axfr retrieve zone params
func (o *AxfrRetrieveZoneParams) WithZoneID(zoneID string) *AxfrRetrieveZoneParams {
	o.SetZoneID(zoneID)
	return o
}

// SetZoneID adds the zoneId to the axfr retrieve zone params
func (o *AxfrRetrieveZoneParams) SetZoneID(zoneID string) {
	o.ZoneID = zoneID
}

// WriteToRequest writes these params to a swagger request
func (o *AxfrRetrieveZoneParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}

	// path param zone_id
	if err := r.SetPathParam("zone_id", o.ZoneID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
