// Code generated by go-swagger; DO NOT EDIT.

package zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/models"
)

// CreateZoneReader is a Reader for the CreateZone structure.
type CreateZoneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateZoneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateZoneCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateZoneCreated creates a CreateZoneCreated with default headers values
func NewCreateZoneCreated() *CreateZoneCreated {
	return &CreateZoneCreated{}
}

/* CreateZoneCreated describes a response with status code 201, with default header values.

A zone
*/
type CreateZoneCreated struct {
	Payload *models.Zone
}

func (o *CreateZoneCreated) Error() string {
	return fmt.Sprintf("[POST /servers/{server_id}/zones][%d] createZoneCreated  %+v", 201, o.Payload)
}
func (o *CreateZoneCreated) GetPayload() *models.Zone {
	return o.Payload
}

func (o *CreateZoneCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Zone)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
