// Code generated by go-swagger; DO NOT EDIT.

package zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/models"
)

// ListZonesReader is a Reader for the ListZones structure.
type ListZonesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListZonesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListZonesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListZonesOK creates a ListZonesOK with default headers values
func NewListZonesOK() *ListZonesOK {
	return &ListZonesOK{}
}

/* ListZonesOK describes a response with status code 200, with default header values.

An array of Zones
*/
type ListZonesOK struct {
	Payload []*models.Zone
}

func (o *ListZonesOK) Error() string {
	return fmt.Sprintf("[GET /servers/{server_id}/zones][%d] listZonesOK  %+v", 200, o.Payload)
}
func (o *ListZonesOK) GetPayload() []*models.Zone {
	return o.Payload
}

func (o *ListZonesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
