// Code generated by go-swagger; DO NOT EDIT.

package zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewNotifyZoneParams creates a new NotifyZoneParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNotifyZoneParams() *NotifyZoneParams {
	return &NotifyZoneParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNotifyZoneParamsWithTimeout creates a new NotifyZoneParams object
// with the ability to set a timeout on a request.
func NewNotifyZoneParamsWithTimeout(timeout time.Duration) *NotifyZoneParams {
	return &NotifyZoneParams{
		timeout: timeout,
	}
}

// NewNotifyZoneParamsWithContext creates a new NotifyZoneParams object
// with the ability to set a context for a request.
func NewNotifyZoneParamsWithContext(ctx context.Context) *NotifyZoneParams {
	return &NotifyZoneParams{
		Context: ctx,
	}
}

// NewNotifyZoneParamsWithHTTPClient creates a new NotifyZoneParams object
// with the ability to set a custom HTTPClient for a request.
func NewNotifyZoneParamsWithHTTPClient(client *http.Client) *NotifyZoneParams {
	return &NotifyZoneParams{
		HTTPClient: client,
	}
}

/* NotifyZoneParams contains all the parameters to send to the API endpoint
   for the notify zone operation.

   Typically these are written to a http.Request.
*/
type NotifyZoneParams struct {

	/* ServerID.

	   The id of the server to retrieve
	*/
	ServerID string

	/* ZoneID.

	   The id of the zone to retrieve
	*/
	ZoneID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the notify zone params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NotifyZoneParams) WithDefaults() *NotifyZoneParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the notify zone params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NotifyZoneParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the notify zone params
func (o *NotifyZoneParams) WithTimeout(timeout time.Duration) *NotifyZoneParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the notify zone params
func (o *NotifyZoneParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the notify zone params
func (o *NotifyZoneParams) WithContext(ctx context.Context) *NotifyZoneParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the notify zone params
func (o *NotifyZoneParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the notify zone params
func (o *NotifyZoneParams) WithHTTPClient(client *http.Client) *NotifyZoneParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the notify zone params
func (o *NotifyZoneParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServerID adds the serverID to the notify zone params
func (o *NotifyZoneParams) WithServerID(serverID string) *NotifyZoneParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the notify zone params
func (o *NotifyZoneParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WithZoneID adds the zoneID to the notify zone params
func (o *NotifyZoneParams) WithZoneID(zoneID string) *NotifyZoneParams {
	o.SetZoneID(zoneID)
	return o
}

// SetZoneID adds the zoneId to the notify zone params
func (o *NotifyZoneParams) SetZoneID(zoneID string) {
	o.ZoneID = zoneID
}

// WriteToRequest writes these params to a swagger request
func (o *NotifyZoneParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}

	// path param zone_id
	if err := r.SetPathParam("zone_id", o.ZoneID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
