// Code generated by go-swagger; DO NOT EDIT.

package zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutZoneReader is a Reader for the PutZone structure.
type PutZoneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutZoneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPutZoneNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutZoneNoContent creates a PutZoneNoContent with default headers values
func NewPutZoneNoContent() *PutZoneNoContent {
	return &PutZoneNoContent{}
}

/* PutZoneNoContent describes a response with status code 204, with default header values.

Returns 204 No Content on success.
*/
type PutZoneNoContent struct {
}

func (o *PutZoneNoContent) Error() string {
	return fmt.Sprintf("[PUT /servers/{server_id}/zones/{zone_id}][%d] putZoneNoContent ", 204)
}

func (o *PutZoneNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
