// Code generated by go-swagger; DO NOT EDIT.

package zones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/gonzolino/terraform-provider-powerdns/internal/powerdns/models"
)

// NewPutZoneParams creates a new PutZoneParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutZoneParams() *PutZoneParams {
	return &PutZoneParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutZoneParamsWithTimeout creates a new PutZoneParams object
// with the ability to set a timeout on a request.
func NewPutZoneParamsWithTimeout(timeout time.Duration) *PutZoneParams {
	return &PutZoneParams{
		timeout: timeout,
	}
}

// NewPutZoneParamsWithContext creates a new PutZoneParams object
// with the ability to set a context for a request.
func NewPutZoneParamsWithContext(ctx context.Context) *PutZoneParams {
	return &PutZoneParams{
		Context: ctx,
	}
}

// NewPutZoneParamsWithHTTPClient creates a new PutZoneParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutZoneParamsWithHTTPClient(client *http.Client) *PutZoneParams {
	return &PutZoneParams{
		HTTPClient: client,
	}
}

/* PutZoneParams contains all the parameters to send to the API endpoint
   for the put zone operation.

   Typically these are written to a http.Request.
*/
type PutZoneParams struct {

	/* ServerID.

	   The id of the server to retrieve
	*/
	ServerID string

	// ZoneID.
	ZoneID string

	/* ZoneStruct.

	   The zone struct to patch with
	*/
	ZoneStruct *models.Zone

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put zone params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutZoneParams) WithDefaults() *PutZoneParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put zone params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutZoneParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put zone params
func (o *PutZoneParams) WithTimeout(timeout time.Duration) *PutZoneParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put zone params
func (o *PutZoneParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put zone params
func (o *PutZoneParams) WithContext(ctx context.Context) *PutZoneParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put zone params
func (o *PutZoneParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put zone params
func (o *PutZoneParams) WithHTTPClient(client *http.Client) *PutZoneParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put zone params
func (o *PutZoneParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServerID adds the serverID to the put zone params
func (o *PutZoneParams) WithServerID(serverID string) *PutZoneParams {
	o.SetServerID(serverID)
	return o
}

// SetServerID adds the serverId to the put zone params
func (o *PutZoneParams) SetServerID(serverID string) {
	o.ServerID = serverID
}

// WithZoneID adds the zoneID to the put zone params
func (o *PutZoneParams) WithZoneID(zoneID string) *PutZoneParams {
	o.SetZoneID(zoneID)
	return o
}

// SetZoneID adds the zoneId to the put zone params
func (o *PutZoneParams) SetZoneID(zoneID string) {
	o.ZoneID = zoneID
}

// WithZoneStruct adds the zoneStruct to the put zone params
func (o *PutZoneParams) WithZoneStruct(zoneStruct *models.Zone) *PutZoneParams {
	o.SetZoneStruct(zoneStruct)
	return o
}

// SetZoneStruct adds the zoneStruct to the put zone params
func (o *PutZoneParams) SetZoneStruct(zoneStruct *models.Zone) {
	o.ZoneStruct = zoneStruct
}

// WriteToRequest writes these params to a swagger request
func (o *PutZoneParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param server_id
	if err := r.SetPathParam("server_id", o.ServerID); err != nil {
		return err
	}

	// path param zone_id
	if err := r.SetPathParam("zone_id", o.ZoneID); err != nil {
		return err
	}
	if o.ZoneStruct != nil {
		if err := r.SetBodyParam(o.ZoneStruct); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
